/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 21:57:10 GMT 2020
 */

package application;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import application.AddBankController;
import java.net.URL;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AddBankController_ESTest extends AddBankController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AddBankController addBankController0 = new AddBankController();
      ActionEvent actionEvent0 = new ActionEvent();
      // Undeclared exception!
      try { 
        addBankController0.addBankUser(actionEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("application.AddBankController", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AddBankController addBankController0 = new AddBankController();
      URL uRL0 = MockURL.getHttpExample();
      addBankController0.initialize(uRL0, (ResourceBundle) null);
      assertNull(uRL0.getQuery());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AddBankController addBankController0 = new AddBankController();
      ActionEvent actionEvent0 = new ActionEvent();
      // Undeclared exception!
      try { 
        addBankController0.retunindex(actionEvent0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javafx.scene.layout.Region
         //
         verifyException("application.share.Utils", e);
      }
  }
}
