/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 22:13:23 GMT 2020
 */

package application;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import application.LotNoList;
import javafx.stage.Stage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LotNoList_ESTest extends LotNoList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LotNoList lotNoList0 = null;
      try {
        lotNoList0 = new LotNoList();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.TableView
         //
         verifyException("application.LotNoList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Stage stage0 = mock(Stage.class, new ViolatedAssumptionAnswer());
      LotNoList lotNoList0 = null;
      try {
        lotNoList0 = new LotNoList(stage0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.TableView
         //
         verifyException("application.LotNoList", e);
      }
  }
}
