/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 21:53:19 GMT 2020
 */

package application;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import application.AddUserAuctionController;
import java.io.StringReader;
import java.net.URL;
import java.util.PropertyResourceBundle;
import javafx.event.ActionEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AddUserAuctionController_ESTest extends AddUserAuctionController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AddUserAuctionController addUserAuctionController0 = new AddUserAuctionController();
      ActionEvent actionEvent0 = new ActionEvent();
      // Undeclared exception!
      try { 
        addUserAuctionController0.addBankUser(actionEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("application.AddUserAuctionController", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AddUserAuctionController addUserAuctionController0 = new AddUserAuctionController();
      // Undeclared exception!
      try { 
        addUserAuctionController0.retunindex((ActionEvent) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.BorderPane
         //
         verifyException("application.share.Utils", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AddUserAuctionController addUserAuctionController0 = new AddUserAuctionController();
      URL uRL0 = MockURL.getFileExample();
      StringReader stringReader0 = new StringReader("}EnpBQ\"._");
      PropertyResourceBundle propertyResourceBundle0 = new PropertyResourceBundle(stringReader0);
      addUserAuctionController0.initialize(uRL0, propertyResourceBundle0);
      assertNull(uRL0.getQuery());
  }
}
