/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 21:32:01 GMT 2020
 */

package application;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import application.AuctionList;
import javafx.stage.Stage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AuctionList_ESTest extends application.AuctionList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AuctionList auctionList0 = null;
      try {
        auctionList0 = new AuctionList((Stage) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.TableView
         //
         verifyException("application.AuctionList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AuctionList auctionList0 = null;
      try {
        auctionList0 = new AuctionList();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.TableView
         //
         verifyException("application.AuctionList", e);
      }
  }
}
