/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 21:24:56 GMT 2020
 */

package application;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import application.AuctionUser;
import javafx.stage.Stage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AuctionUser_ESTest extends AuctionUser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AuctionUser auctionUser0 = null;
      try {
        auctionUser0 = new AuctionUser((Stage) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.TableView
         //
         verifyException("application.AuctionUser", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AuctionUser auctionUser0 = null;
      try {
        auctionUser0 = new AuctionUser();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.TableView
         //
         verifyException("application.AuctionUser", e);
      }
  }
}
