/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 19:21:13 GMT 2020
 */

package application;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import application.LotListController;
import java.net.URL;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LotListController_ESTest extends application.LotListController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LotListController lotListController0 = new LotListController();
      // Undeclared exception!
      try { 
        lotListController0.retunindex((ActionEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("application.LotListController", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LotListController lotListController0 = new LotListController();
      ActionEvent actionEvent0 = new ActionEvent();
      // Undeclared exception!
      try { 
        lotListController0.redistAuction(actionEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("application.LotListController", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LotListController lotListController0 = new LotListController();
      ActionEvent actionEvent0 = new ActionEvent();
      // Undeclared exception!
      try { 
        lotListController0.retunindex(actionEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // javafx.event.Event$$Lambda$40/1745872711 cannot be cast to javafx.scene.Node
         //
         verifyException("application.LotListController", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LotListController lotListController0 = new LotListController();
      URL uRL0 = MockURL.getHttpExample();
      lotListController0.initialize(uRL0, (ResourceBundle) null);
      assertEquals((-1), uRL0.getPort());
  }
}
