/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 19:17:43 GMT 2020
 */

package application;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import application.NewHouseController;
import java.io.StringReader;
import java.net.URL;
import java.util.PropertyResourceBundle;
import javafx.event.ActionEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NewHouseController_ESTest extends application.NewHouseController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ActionEvent actionEvent0 = new ActionEvent();
      NewHouseController newHouseController0 = new NewHouseController();
      // Undeclared exception!
      try { 
        newHouseController0.redistAuction(actionEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("application.NewHouseController", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NewHouseController newHouseController0 = new NewHouseController();
      URL uRL0 = MockURL.getHttpExample();
      StringReader stringReader0 = new StringReader("Ie@");
      PropertyResourceBundle propertyResourceBundle0 = new PropertyResourceBundle(stringReader0);
      newHouseController0.initialize(uRL0, propertyResourceBundle0);
      assertEquals((-1), uRL0.getPort());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NewHouseController newHouseController0 = new NewHouseController();
      ActionEvent actionEvent0 = new ActionEvent();
      // Undeclared exception!
      try { 
        newHouseController0.retunindex(actionEvent0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.stage.Screen
         //
         verifyException("javafx.stage.Window", e);
      }
  }
}
