/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 21:58:25 GMT 2020
 */

package application.share;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import application.share.AlertBox;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AlertBox_ESTest extends AlertBox_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AlertBox alertBox0 = new AlertBox();
      // Undeclared exception!
      try { 
        alertBox0.display("", "");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.stage.Screen
         //
         verifyException("javafx.stage.Window", e);
      }
  }
}
