/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 21:43:23 GMT 2020
 */

package application.share;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import application.share.Utils;
import application.share.entity.BankAccount;
import javafx.stage.Stage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Utils_ESTest extends Utils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        Utils.getDetails();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("application.share.Utils", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      Utils.bankuser = bankAccount0;
      // Undeclared exception!
      try { 
        Utils.getDetailsByType((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("application.share.Utils", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Utils.getDetailsByType("Prompt");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Utils utils0 = new Utils();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        Utils.start((Stage) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.BorderPane
         //
         verifyException("application.share.Utils", e);
      }
  }
}
