/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 19:04:12 GMT 2020
 */

package application.share;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import application.Main;
import application.share.Utils;
import application.share.entity.Auction;
import java.nio.channels.NotYetConnectedException;
import java.nio.channels.SocketChannel;
import javafx.stage.Stage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Utils_ESTest extends Utils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Auction auction0 = new Auction("", "", "@#G@getdetails_");
      SocketChannel socketChannel0 = SocketChannel.open();
      Main.sc = socketChannel0;
      Utils.auction = auction0;
      // Undeclared exception!
      try { 
        Utils.getDetailsByType("");
        fail("Expecting exception: NotYetConnectedException");
      
      } catch(NotYetConnectedException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SocketChannel socketChannel0 = SocketChannel.open();
      Main.sc = socketChannel0;
      Auction auction0 = new Auction("", "", "");
      Utils.auction = auction0;
      // Undeclared exception!
      try { 
        Utils.getDetails();
        fail("Expecting exception: NotYetConnectedException");
      
      } catch(NotYetConnectedException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Auction auction0 = new Auction("", "", "@#G@getdetails_");
      Utils.auction = auction0;
      // Undeclared exception!
      try { 
        Utils.getDetailsByType("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("application.share.Utils", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Utils.getDetailsByType("");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Utils.getDetails();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Utils utils0 = new Utils();
      Auction auction0 = new Auction("", "", "");
      utils0.auction = auction0;
      // Undeclared exception!
      try { 
        Utils.getDetails();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("application.share.Utils", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try { 
        Utils.start((Stage) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.BorderPane
         //
         verifyException("application.share.Utils", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        Utils.start();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.stage.Screen
         //
         verifyException("javafx.stage.Window", e);
      }
  }
}
