/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 21:16:02 GMT 2020
 */

package application.share.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import application.share.entity.BankAccount;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BankAccount_ESTest extends application.share.entity.BankAccount_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.state = "application.share.entity.BankAccount";
      String string0 = bankAccount0.getState();
      assertEquals("application.share.entity.BankAccount", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.state = "";
      String string0 = bankAccount0.getState();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.setMoney("%<j}kqfiCv7");
      String string0 = bankAccount0.getMoney();
      assertEquals("%<j}kqfiCv7", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.setBankName("j0#A3|7$>mBZ'=3");
      String string0 = bankAccount0.getBankName();
      assertEquals("j0#A3|7$>mBZ'=3", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.setBankKey("TM ");
      String string0 = bankAccount0.getBankKey();
      assertEquals("TM ", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.setBankAccount("0T_z\")/");
      String string0 = bankAccount0.getBankAccount();
      assertEquals("0T_z\")/", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.setBankKey("");
      String string0 = bankAccount0.getBankKey();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.setState("application.share.entity.BankAccount");
      assertNull(bankAccount0.getBankAccount());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.setBankName("");
      String string0 = bankAccount0.getBankName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      String string0 = bankAccount0.getBankName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      String string0 = bankAccount0.getMoney();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.setMoney("");
      String string0 = bankAccount0.getMoney();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      bankAccount0.setBankAccount("");
      String string0 = bankAccount0.getBankAccount();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      String string0 = bankAccount0.getBankKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      String string0 = bankAccount0.getState();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount();
      String string0 = bankAccount0.getBankAccount();
      assertNull(string0);
  }
}
