/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 20:25:45 GMT 2020
 */

package application.share.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import application.share.entity.Lot;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Lot_ESTest extends application.share.entity.Lot_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      lot0.setUserName("kKvpJ");
      lot0.getUserName();
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      lot0.setState((String) null);
      String string0 = lot0.getState();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Lot lot0 = new Lot("", "", "Mflp`#4ZR0&V");
      lot0.setState("");
      String string0 = lot0.getState();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      lot0.setPrijectId((String) null);
      lot0.getPrijectId();
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Lot lot0 = new Lot((String) null, "", "");
      String string0 = lot0.getPrijectId();
      assertEquals("0", lot0.getState());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Lot lot0 = new Lot("", "ih)Ens=S", (String) null);
      String string0 = lot0.getName();
      assertNull(string0);
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      lot0.setName("");
      lot0.getName();
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      lot0.setMoney(".b{#MqasvP]E28?k@1");
      lot0.getMoney();
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Lot lot0 = new Lot((String) null, "", "");
      lot0.setMoney("");
      lot0.getMoney();
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Lot lot0 = new Lot((String) null, "", "");
      String string0 = lot0.getAuctionId();
      assertNull(string0);
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      String string0 = lot0.getAuctionId();
      assertEquals("", string0);
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      lot0.getPrijectId();
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      lot0.getMoney();
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      String string0 = lot0.getState();
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      lot0.getUserName();
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      lot0.setAuctionId("kKvpJ");
      lot0.getAuctionId();
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      lot0.setUserName("");
      lot0.getUserName();
      assertEquals("0", lot0.getState());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Lot lot0 = new Lot("", ".b{#MqasvP]E28?k@1", "=LBX-wq{(cHd+sTq@z");
      String string0 = lot0.getName();
      assertEquals("0", lot0.getState());
      assertEquals("=LBX-wq{(cHd+sTq@z", string0);
  }
}
