/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 20:26:27 GMT 2020
 */

package application.share.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import application.share.entity.UserRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UserRequest_ESTest extends application.share.entity.UserRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserRequest userRequest0 = new UserRequest("", (String) null, (String) null);
      userRequest0.setUserName((String) null);
      String string0 = userRequest0.getUserName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserRequest userRequest0 = new UserRequest("", (String) null, (String) null);
      userRequest0.setUserName("0]zl;Kfv=0nt{rjrF");
      String string0 = userRequest0.getUserName();
      assertEquals("0]zl;Kfv=0nt{rjrF", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UserRequest userRequest0 = new UserRequest("*Kd=9Q2`I%]Hvf#<", "*Kd=9Q2`I%]Hvf#<", "M@,4Qz,UI+K{");
      userRequest0.setGetAuctionKey((String) null);
      String string0 = userRequest0.getGetAuctionKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UserRequest userRequest0 = new UserRequest("", (String) null, (String) null);
      userRequest0.setGetAuctionKey("Su9@LEj{Yl");
      String string0 = userRequest0.getGetAuctionKey();
      assertEquals("Su9@LEj{Yl", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UserRequest userRequest0 = new UserRequest("application.share.entity.UserRequest", (String) null, (String) null);
      String string0 = userRequest0.getBankKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UserRequest userRequest0 = new UserRequest("", (String) null, (String) null);
      userRequest0.setBankKey("0]zl;Kfv=0nt{rjrF");
      String string0 = userRequest0.getBankKey();
      assertEquals("0]zl;Kfv=0nt{rjrF", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      UserRequest userRequest0 = new UserRequest("", "", "");
      String string0 = userRequest0.getBankKey();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      UserRequest userRequest0 = new UserRequest("", "", "");
      String string0 = userRequest0.getUserName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      UserRequest userRequest0 = new UserRequest("", "", "");
      String string0 = userRequest0.getGetAuctionKey();
      assertEquals("", string0);
  }
}
